name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: yarn install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: '增加提示词，扩展更多的智能对话可能，GPT 可以根据你扮演的角色给予更丰富的对话'
          releaseDraft: false
          prerelease: false
  #  generate-version-control-file:
  #    runs-on: ubuntu-latest
  #    needs: [ publish-tauri ]
  #
  #    steps:
  #      - uses: actions/checkout@v2
  #      - run: yarn
  #      - run: yarn deploy
  #        env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #
  #      - name: Generate uploader.json file
  #        uses: peaceiris/actions-gh-pages@v3
  #        with:
  #          github_token: ${{ secrets.GITHUB_TOKEN }}
  #          publish_dir: ./updater
  #          force_orphan: true
  generate-github-page:
    runs-on: ubuntu-latest
    needs: [ publish-tauri ]

    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build:browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: generate static website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser
          force_orphan: true
